version: '2'
services:
  service-app:
    build: ./service/target
    networks:
     - backend
    depends_on:
     - db

  booking-app:
    build: ./booking/target
    networks:
     - backend
    depends_on:
     - db

  db:
    hostname: redis
    image: "redis:alpine"
    ports:
     - "6379:6379"
    networks:
     - backend

  nginx-lb:
    container_name: nginx-lb
    image: nginx:1.13
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
     - backend
    depends_on:
     - service-app
     - booking-app


networks:
  backend:
    driver: bridge